export const CUSTOMER_INDUSTRIES = [
  "Agriculture",
  "Retail",
  "Distribution",
  "Export",
] as const;

export const CUSTOMER_CITIES = [
  "Santa Cruz",
  "La Paz",
  "Cochabamba",
  "Trinidad",
  "Beni",
  "Oruro",
  "Potosí",
  "Sucre",
] as const;

export const CUSTOMER_INDUSTRY_LABELS: Record<string, string> = {
  Agriculture: "Agricultura",
  Retail: "Minorista",
  Distribution: "Distribución",
  Export: "Exportación",
};

export const CUSTOMER_FORM_COPY = {
  addTitle: "Agregar cliente",
  editTitle: "Editar cliente",
  save: "Guardar cliente",
  cancel: "Cancelar",
  name: "Nombre",
  namePlaceholder: "Ej. Agro Norte SRL",
  email: "Correo electrónico",
  emailPlaceholder: "contacto@empresa.bo",
  phone: "Teléfono",
  phonePlaceholder: "+591 3 333-0000",
  city: "Ciudad",
  industry: "Industria",
  status: "Estado",
  active: "Activo",
  inactive: "Inactivo",
  select: "Seleccionar…",
  nameRequired: "El nombre es obligatorio.",
  emailRequired: "El correo es obligatorio.",
  emailInvalid: "Ingresa un correo válido.",
} as const;

export const CUSTOMER_PAGE_COPY = {
  title: "Clientes",
  subtitle: "Todos los clientes y el estado de sus cuentas",
  addButton: "Agregar cliente",
  export: "Exportar",
  overview: "Resumen",
  allCustomers: "Todos los clientes",
  totalCustomers: "Total de clientes",
  active: "Activos",
  totalOutstanding: "Saldo pendiente",
  atRisk: "En riesgo",
  allTime: "Histórico",
  currentlyBuying: "Comprando actualmente",
  unpaidBalances: "Saldos sin pagar",
  highOverdueRisk: "Alto riesgo de mora",
  searchPlaceholder: "Buscar por nombre de cliente…",
  status: "Estado",
  risk: "Riesgo",
  all: "Todos",
  allIndustries: "Todas las industrias",
  allCities: "Todas las ciudades",
  clearAll: "Limpiar todo",
  customer: "Cliente",
  city: "Ciudad",
  industry: "Industria",
  contact: "Contacto",
  totalInvoiced: "Total facturado",
  totalPaid: "Total pagado",
  outstanding: "Pendiente",
  settled: "Liquidado",
  byIndustry: "Por industria",
  noCustomers: "No se encontraron clientes",
  noCustomersEmpty: "Agrega tu primer cliente con el botón de arriba.",
  noCustomersFilter: "Ningún cliente coincide con los filtros actuales.",
  edit: "Editar",
  delete: "Eliminar",
  deleteTitle: "Eliminar cliente",
  deleteMessage: (name: string) =>
    `¿Eliminar permanentemente a «${name}»? Esta acción no se puede deshacer.`,
  deleteConfirm: "Eliminar",
  actions: "Acciones",
} as const;
