-- Receivable payment events + extended bank ledger reference types.

CREATE TABLE IF NOT EXISTS public.company_receivable_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  invoice_id bigint NOT NULL REFERENCES public.company_receivables(id) ON DELETE CASCADE,
  amount numeric(14, 2) NOT NULL CHECK (amount > 0),
  payment_date date NOT NULL,
  payment_method text NOT NULL,
  bank_account_id uuid REFERENCES public.company_bank_accounts(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS company_receivable_payments_company_idx
  ON public.company_receivable_payments(company_id);

CREATE INDEX IF NOT EXISTS company_receivable_payments_invoice_idx
  ON public.company_receivable_payments(invoice_id);

ALTER TABLE public.company_receivable_payments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivable_payments_select_member_or_superadmin') THEN
    CREATE POLICY company_receivable_payments_select_member_or_superadmin ON public.company_receivable_payments
      FOR SELECT TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivable_payments.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivable_payments_insert_member_or_superadmin') THEN
    CREATE POLICY company_receivable_payments_insert_member_or_superadmin ON public.company_receivable_payments
      FOR INSERT TO authenticated WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivable_payments.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivable_payments_delete_member_or_superadmin') THEN
    CREATE POLICY company_receivable_payments_delete_member_or_superadmin ON public.company_receivable_payments
      FOR DELETE TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivable_payments.company_id AND cm.user_id = auth.uid())
      );
  END IF;
END $$;

-- Support numeric reference ids (receivable payments, PO/SO) alongside uuid expense/revenue ids.
ALTER TABLE public.company_bank_transactions
  ALTER COLUMN reference_id TYPE text USING reference_id::text;

ALTER TABLE public.company_bank_transactions
  DROP CONSTRAINT IF EXISTS company_bank_transactions_reference_type_check;

ALTER TABLE public.company_bank_transactions
  ADD CONSTRAINT company_bank_transactions_reference_type_check CHECK (
    reference_type IN (
      'expense', 'revenue', 'manual', 'transfer', 'opening',
      'receivable', 'purchase_order', 'sales_order'
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS company_bank_transactions_receivable_ref_idx
  ON public.company_bank_transactions(reference_id)
  WHERE reference_type = 'receivable';

CREATE UNIQUE INDEX IF NOT EXISTS company_bank_transactions_purchase_order_ref_idx
  ON public.company_bank_transactions(reference_id)
  WHERE reference_type = 'purchase_order';

CREATE UNIQUE INDEX IF NOT EXISTS company_bank_transactions_sales_order_ref_idx
  ON public.company_bank_transactions(reference_id)
  WHERE reference_type = 'sales_order';

-- Remove linked bank row when a receivable payment is deleted.
CREATE OR REPLACE FUNCTION public.trg_remove_receivable_payment_bank_tx()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.company_bank_transactions
  WHERE reference_type = 'receivable'
    AND reference_id = OLD.id::text;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS company_receivable_payments_remove_bank_tx ON public.company_receivable_payments;
CREATE TRIGGER company_receivable_payments_remove_bank_tx
  AFTER DELETE ON public.company_receivable_payments
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_remove_receivable_payment_bank_tx();

-- Inventory order payment metadata (set when received / fulfilled).
ALTER TABLE public.company_inventory_purchase_orders
  ADD COLUMN IF NOT EXISTS payment_method text,
  ADD COLUMN IF NOT EXISTS bank_account_id uuid
    REFERENCES public.company_bank_accounts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS received_date date;

ALTER TABLE public.company_inventory_sales_orders
  ADD COLUMN IF NOT EXISTS payment_method text,
  ADD COLUMN IF NOT EXISTS bank_account_id uuid
    REFERENCES public.company_bank_accounts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS fulfilled_date date;
