CREATE TABLE IF NOT EXISTS public.company_receivables (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  customer_name text NOT NULL,
  invoice_number text NOT NULL,
  amount numeric(14, 2) NOT NULL CHECK (amount > 0),
  amount_paid numeric(14, 2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  due_date date NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS company_receivables_company_id_idx
  ON public.company_receivables(company_id);

CREATE INDEX IF NOT EXISTS company_receivables_due_date_idx
  ON public.company_receivables(company_id, due_date DESC);

ALTER TABLE public.company_receivables ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivables_select_member_or_superadmin') THEN
    CREATE POLICY company_receivables_select_member_or_superadmin ON public.company_receivables
      FOR SELECT TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivables.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivables_insert_member_or_superadmin') THEN
    CREATE POLICY company_receivables_insert_member_or_superadmin ON public.company_receivables
      FOR INSERT TO authenticated WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivables.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivables_update_member_or_superadmin') THEN
    CREATE POLICY company_receivables_update_member_or_superadmin ON public.company_receivables
      FOR UPDATE TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivables.company_id AND cm.user_id = auth.uid())
      ) WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivables.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_receivables_delete_member_or_superadmin') THEN
    CREATE POLICY company_receivables_delete_member_or_superadmin ON public.company_receivables
      FOR DELETE TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_receivables.company_id AND cm.user_id = auth.uid())
      );
  END IF;
END $$;
