CREATE TABLE IF NOT EXISTS public.company_inventory_suppliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text,
  email text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_inventory_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name text NOT NULL,
  sku text NOT NULL,
  category text NOT NULL,
  unit text NOT NULL,
  quantity numeric(14, 2) NOT NULL DEFAULT 0,
  min_threshold numeric(14, 2) NOT NULL DEFAULT 0,
  cost_price numeric(14, 2) NOT NULL DEFAULT 0,
  sale_price numeric(14, 2) NOT NULL DEFAULT 0,
  supplier_id bigint,
  description text,
  active boolean NOT NULL DEFAULT true,
  created_at date NOT NULL DEFAULT CURRENT_DATE,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_inventory_purchase_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  po_number text NOT NULL,
  supplier_id bigint NOT NULL,
  expected_date date,
  status text NOT NULL,
  total numeric(14, 2) NOT NULL DEFAULT 0,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_inventory_sales_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  so_number text NOT NULL,
  customer_id bigint NOT NULL,
  status text NOT NULL,
  total numeric(14, 2) NOT NULL DEFAULT 0,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_inventory_adjustments (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  product_id bigint NOT NULL,
  quantity_change numeric(14, 2) NOT NULL,
  reason text NOT NULL,
  user_label text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS company_inventory_products_company_idx ON public.company_inventory_products(company_id);
CREATE INDEX IF NOT EXISTS company_inventory_po_company_idx ON public.company_inventory_purchase_orders(company_id);
CREATE INDEX IF NOT EXISTS company_inventory_so_company_idx ON public.company_inventory_sales_orders(company_id);

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'company_inventory_suppliers',
    'company_inventory_products',
    'company_inventory_purchase_orders',
    'company_inventory_sales_orders',
    'company_inventory_adjustments'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = t || '_select') THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (
          EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = ''superadmin'')
          OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = %I.company_id AND cm.user_id = auth.uid())
        )', t || '_select', t, t
      );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = t || '_insert') THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (
          EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = ''superadmin'')
          OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = %I.company_id AND cm.user_id = auth.uid())
        )', t || '_insert', t, t
      );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = t || '_update') THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (
          EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = ''superadmin'')
          OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = %I.company_id AND cm.user_id = auth.uid())
        ) WITH CHECK (
          EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = ''superadmin'')
          OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = %I.company_id AND cm.user_id = auth.uid())
        )', t || '_update', t, t, t
      );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = t || '_delete') THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (
          EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = ''superadmin'')
          OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = %I.company_id AND cm.user_id = auth.uid())
        )', t || '_delete', t, t
      );
    END IF;
  END LOOP;
END $$;
