CREATE TABLE IF NOT EXISTS public.company_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text,
  phone text,
  city text,
  industry text,
  status text NOT NULL DEFAULT 'Active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS company_customers_company_id_idx
  ON public.company_customers(company_id);

ALTER TABLE public.company_customers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_customers_select_member_or_superadmin') THEN
    CREATE POLICY company_customers_select_member_or_superadmin ON public.company_customers
      FOR SELECT TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_customers.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_customers_insert_member_or_superadmin') THEN
    CREATE POLICY company_customers_insert_member_or_superadmin ON public.company_customers
      FOR INSERT TO authenticated WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_customers.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_customers_update_member_or_superadmin') THEN
    CREATE POLICY company_customers_update_member_or_superadmin ON public.company_customers
      FOR UPDATE TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_customers.company_id AND cm.user_id = auth.uid())
      ) WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_customers.company_id AND cm.user_id = auth.uid())
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'company_customers_delete_member_or_superadmin') THEN
    CREATE POLICY company_customers_delete_member_or_superadmin ON public.company_customers
      FOR DELETE TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
        OR EXISTS (SELECT 1 FROM public.company_members cm WHERE cm.company_id = company_customers.company_id AND cm.user_id = auth.uid())
      );
  END IF;
END $$;
