import type { ExpenseRecord, ReceivableRecord, RevenueRecord } from "./types";

export const DEFAULT_CURRENCY: "Bs" = "Bs";

export const initialRevenueRecords: RevenueRecord[] = [
  // ─── January 2026 (152,000 Bs active revenue) ───────────────────────────────
  {
    id: "rev-2026-01-01",
    date: "2026-01-28",
    sourceClient: "Distribuidora Norte",
    productService: "Product Export — FOB Shipment",
    category: "Export Sale",
    amount: 85000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0108",
    notes: "Q1 export contract — lot 1",
  },
  {
    id: "rev-2026-01-02",
    date: "2026-01-22",
    sourceClient: "Mercado Central La Paz",
    productService: "Wholesale Product — Batch A",
    category: "Wholesale",
    amount: 32000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0095",
    notes: "",
  },
  {
    id: "rev-2026-01-03",
    date: "2026-01-15",
    sourceClient: "Cooperativa Yungas",
    productService: "Local Delivery — North Route",
    category: "Local Sale",
    amount: 22000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Cash",
    invoiceNumber: "INV-2026-0082",
    notes: "",
  },
  {
    id: "rev-2026-01-04",
    date: "2026-01-10",
    sourceClient: "Exportadora Oriente",
    productService: "Import logistics coordination — January",
    category: "Import Sale",
    amount: 8000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0074",
    notes: "",
  },
  {
    id: "rev-2026-01-05",
    date: "2026-01-08",
    sourceClient: "Agro Bolivia SRL",
    productService: "Brokerage commission — soybean lot",
    category: "Commission",
    amount: 5000,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0070",
    notes: "Net-30",
  },
  // ─── February 2026 (138,000 Bs) ─────────────────────────────────────────────
  {
    id: "rev-2026-02-01",
    date: "2026-02-25",
    sourceClient: "Global Grain Partners",
    productService: "Export Contract — Q1 Partial",
    category: "Export Sale",
    amount: 72000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0156",
    notes: "",
  },
  {
    id: "rev-2026-02-02",
    date: "2026-02-18",
    sourceClient: "Mercado Central La Paz",
    productService: "Wholesale — Central Market Lot",
    category: "Wholesale",
    amount: 38000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0142",
    notes: "",
  },
  {
    id: "rev-2026-02-03",
    date: "2026-02-12",
    sourceClient: "Cliente Santa Cruz",
    productService: "Local Sale — Retail Depot",
    category: "Local Sale",
    amount: 18000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0131",
    notes: "",
  },
  {
    id: "rev-2026-02-04",
    date: "2026-02-05",
    sourceClient: "Cooperativa Yungas",
    productService: "Retail Product — 200 Units",
    category: "Retail",
    amount: 10000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Cash",
    invoiceNumber: "INV-2026-0118",
    notes: "",
  },
  // ─── March 2026 (165,000 Bs) ────────────────────────────────────────────────
  {
    id: "rev-2026-03-01",
    date: "2026-03-26",
    sourceClient: "Global Grain Partners",
    productService: "Export Shipment — March",
    category: "Export Sale",
    amount: 95000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0228",
    notes: "",
  },
  {
    id: "rev-2026-03-02",
    date: "2026-03-18",
    sourceClient: "Distribuidora Norte",
    productService: "Wholesale Product — Batch B",
    category: "Wholesale",
    amount: 42000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0214",
    notes: "",
  },
  {
    id: "rev-2026-03-03",
    date: "2026-03-12",
    sourceClient: "Exportadora Oriente",
    productService: "Import clearance and forwarding — March",
    category: "Import Sale",
    amount: 15000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0201",
    notes: "",
  },
  {
    id: "rev-2026-03-04",
    date: "2026-03-06",
    sourceClient: "Finca El Palmar",
    productService: "Direct Sale — Local Route",
    category: "Local Sale",
    amount: 13000,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0190",
    notes: "",
  },
  // ─── April 2026 supplements (with rev-8, rev-9, rev-10 → 178,000 Bs) ───────
  {
    id: "rev-2026-04-01",
    date: "2026-04-12",
    sourceClient: "Exportadora Oriente",
    productService: "Export Advance — April Contract",
    category: "Export Sale",
    amount: 28000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0335",
    notes: "",
  },
  {
    id: "rev-2026-04-02",
    date: "2026-04-05",
    sourceClient: "Cliente Santa Cruz",
    productService: "Local Sale — Bulk Lot",
    category: "Local Sale",
    amount: 22600,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Cash",
    invoiceNumber: "INV-2026-0320",
    notes: "",
  },
  {
    id: "rev-1",
    date: "2026-05-16",
    sourceClient: "Distribuidora Norte",
    productService: "Product Sale — 28 Units",
    category: "Export Sale",
    amount: 67200,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0412",
    notes: "FOB Santa Cruz shipment",
  },
  {
    id: "rev-2",
    date: "2026-05-14",
    sourceClient: "Mercado Central La Paz",
    productService: "Wholesale Product — Lot C",
    category: "Wholesale",
    amount: 38500,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0408",
    notes: "",
  },
  {
    id: "rev-3",
    date: "2026-05-12",
    sourceClient: "Agro Bolivia SRL",
    productService: "Soybean brokerage commission",
    category: "Commission",
    amount: 4200,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0405",
    notes: "Net-30 terms",
  },
  {
    id: "rev-4",
    date: "2026-05-10",
    sourceClient: "Exportadora Oriente",
    productService: "Import logistics coordination",
    category: "Import Sale",
    amount: 8900,
    currency: "Bs",
    status: "Overdue",
    paymentMethod: "Check",
    invoiceNumber: "INV-2026-0399",
    notes: "45 days outstanding",
  },
  {
    id: "rev-5",
    date: "2026-05-08",
    sourceClient: "Finca El Palmar",
    productService: "Business Consulting — Q2",
    category: "Service Fee",
    amount: 5500,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Card",
    invoiceNumber: "INV-2026-0394",
    notes: "",
  },
  {
    id: "rev-6",
    date: "2026-05-05",
    sourceClient: "Cooperativa Yungas",
    productService: "Retail Product — 120 Units",
    category: "Retail",
    amount: 7200,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Cash",
    invoiceNumber: "INV-2026-0388",
    notes: "",
  },
  {
    id: "rev-7",
    date: "2026-05-02",
    sourceClient: "Cliente Santa Cruz",
    productService: "Bulk Product — Storage Lot",
    category: "Local Sale",
    amount: 15800,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0381",
    notes: "Awaiting delivery confirmation",
  },
  {
    id: "rev-8",
    date: "2026-04-28",
    sourceClient: "Global Grain Partners",
    productService: "Export Contract — Q2",
    category: "Export Sale",
    amount: 124000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0370",
    notes: "Partial advance received",
  },
  {
    id: "rev-9",
    date: "2026-04-22",
    sourceClient: "Distribuidora Norte",
    productService: "Cancelled pre-order",
    category: "Other",
    amount: 0,
    currency: "Bs",
    status: "Cancelled",
    paymentMethod: "Other",
    invoiceNumber: "INV-2026-0355",
    notes: "Client cancelled before shipment",
  },
  {
    id: "rev-10",
    date: "2026-04-18",
    sourceClient: "Mercado Central La Paz",
    productService: "Import clearance service package",
    category: "Service Fee",
    amount: 3400,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0348",
    notes: "",
  },
  // ─── May 2026 supplements (with rev-1…rev-7 → 185,400 Bs) ───────────────────
  {
    id: "rev-2026-05-01",
    date: "2026-05-20",
    sourceClient: "Global Grain Partners",
    productService: "Export contract advance — May shipment",
    category: "Export Sale",
    amount: 25000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0420",
    notes: "",
  },
  {
    id: "rev-2026-05-02",
    date: "2026-05-18",
    sourceClient: "Hacienda San Miguel",
    productService: "Wholesale — Regional Route",
    category: "Wholesale",
    amount: 13100,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0416",
    notes: "",
  },
  // ─── June 2026 (195,000 Bs) ─────────────────────────────────────────────────
  {
    id: "rev-2026-06-01",
    date: "2026-06-22",
    sourceClient: "Distribuidora Norte",
    productService: "Export Shipment — June FOB",
    category: "Export Sale",
    amount: 98000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0512",
    notes: "",
  },
  {
    id: "rev-2026-06-02",
    date: "2026-06-15",
    sourceClient: "Mercado Central La Paz",
    productService: "Wholesale Product — June Lot",
    category: "Wholesale",
    amount: 52000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0498",
    notes: "",
  },
  {
    id: "rev-2026-06-03",
    date: "2026-06-10",
    sourceClient: "Exportadora Oriente",
    productService: "Import forwarding — June intake",
    category: "Import Sale",
    amount: 28000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0485",
    notes: "",
  },
  {
    id: "rev-2026-06-04",
    date: "2026-06-05",
    sourceClient: "Finca El Palmar",
    productService: "Business Consulting — Mid-Year",
    category: "Service Fee",
    amount: 17000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Card",
    invoiceNumber: "INV-2026-0472",
    notes: "",
  },
];

export const initialExpenseRecords: ExpenseRecord[] = [
  // ─── January 2026 (110,000 Bs) ──────────────────────────────────────────────
  {
    id: "exp-2026-01-01",
    date: "2026-01-27",
    category: "Labor",
    description: "Field prep and planting crews — all plots",
    vendor: "Cuadrilla Norte",
    amount: 28000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-01-02",
    date: "2026-01-20",
    category: "Supplier Payment",
    description: "Supplies — Operations Q1",
    vendor: "AgroInsumos SA",
    amount: 32000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-01-03",
    date: "2026-01-15",
    category: "Transport",
    description: "Input delivery to plots A and B",
    vendor: "TransAgro Bolivia",
    amount: 18000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-01-04",
    date: "2026-01-10",
    category: "Fuel",
    description: "Diesel — tractors and irrigation pumps",
    vendor: "Estación El Trigal",
    amount: 12000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-2026-01-05",
    date: "2026-01-08",
    category: "Storage",
    description: "Warehouse rent — January",
    vendor: "Depósito Central SC",
    amount: 8000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-01-06",
    date: "2026-01-05",
    category: "Maintenance",
    description: "Irrigation system inspection — all plots",
    vendor: "Servicios Hídricos López",
    amount: 12000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  // ─── February 2026 (115,000 Bs) ─────────────────────────────────────────────
  {
    id: "exp-2026-02-01",
    date: "2026-02-24",
    category: "Labor",
    description: "Mid-season field maintenance",
    vendor: "Cuadrilla Norte",
    amount: 26000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-02-02",
    date: "2026-02-18",
    category: "Supplier Payment",
    description: "Supplies — Bulk Order February",
    vendor: "NutriGanado Bolivia",
    amount: 24000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-02-03",
    date: "2026-02-12",
    category: "Transport",
    description: "Product Transfer — Central Depot",
    vendor: "TransAgro Bolivia",
    amount: 19000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-02-04",
    date: "2026-02-08",
    category: "Fuel",
    description: "Diesel — February operations",
    vendor: "Estación El Trigal",
    amount: 14000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-2026-02-05",
    date: "2026-02-05",
    category: "Supplier Payment",
    description: "Herbicide and crop protection",
    vendor: "AgroInsumos SA",
    amount: 22000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-02-06",
    date: "2026-02-02",
    category: "Packaging",
    description: "Grain sacks and pallet supplies",
    vendor: "Empaques del Valle",
    amount: 10000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Cash",
    notes: "",
  },
  // ─── March 2026 (122,000 Bs) ────────────────────────────────────────────────
  {
    id: "exp-2026-03-01",
    date: "2026-03-25",
    category: "Labor",
    description: "Pre-harvest field crews",
    vendor: "Cuadrilla Norte",
    amount: 30000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-03-02",
    date: "2026-03-18",
    category: "Supplier Payment",
    description: "Operational Supplies — Application",
    vendor: "AgroInsumos SA",
    amount: 28000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-03-03",
    date: "2026-03-12",
    category: "Transport",
    description: "Export prep haulage to port depot",
    vendor: "TransAgro Bolivia",
    amount: 20000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-03-04",
    date: "2026-03-08",
    category: "Fuel",
    description: "Harvest machinery diesel — March",
    vendor: "Estación El Trigal",
    amount: 15000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-2026-03-05",
    date: "2026-03-05",
    category: "Customs",
    description: "Export documentation — March shipment",
    vendor: "Aduanas Express",
    amount: 19000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-03-06",
    date: "2026-03-02",
    category: "Maintenance",
    description: "Combine harvester service",
    vendor: "Maquinaria Agrícola SC",
    amount: 10000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  // ─── April 2026 supplements (with exp-8…exp-10 → 125,000 Bs) ───────────────
  {
    id: "exp-2026-04-01",
    date: "2026-04-15",
    category: "Labor",
    description: "Harvest support — Plot A and B",
    vendor: "Cuadrilla Norte",
    amount: 35000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-04-02",
    date: "2026-04-10",
    category: "Supplier Payment",
    description: "Post-harvest storage treatment supplies",
    vendor: "AgroInsumos SA",
    amount: 32000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-04-03",
    date: "2026-04-08",
    category: "Transport",
    description: "April export and local delivery routes",
    vendor: "TransAgro Bolivia",
    amount: 25000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-04-04",
    date: "2026-04-02",
    category: "Fuel",
    description: "Fleet diesel — April",
    vendor: "Estación El Trigal",
    amount: 10170,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-2026-04-05",
    date: "2026-04-01",
    category: "Taxes",
    description: "Municipal agro operating fees — Q2",
    vendor: "Gobierno Municipal",
    amount: 18000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-1",
    date: "2026-05-15",
    category: "Transport",
    description: "Product Delivery — Regional Depot",
    vendor: "TransAgro Bolivia",
    amount: 4200,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "Invoice #TA-2041",
  },
  {
    id: "exp-2",
    date: "2026-05-14",
    category: "Fuel",
    description: "Diesel for harvest machinery",
    vendor: "Estación El Trigal",
    amount: 1850,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-3",
    date: "2026-05-12",
    category: "Labor",
    description: "Seasonal field workers — Plot B harvest",
    vendor: "Cuadrilla Norte",
    amount: 6800,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Cash",
    notes: "Due end of week",
  },
  {
    id: "exp-4",
    date: "2026-05-10",
    category: "Supplier Payment",
    description: "Supplies — Operations Order",
    vendor: "AgroInsumos SA",
    amount: 12400,
    currency: "Bs",
    status: "Overdue",
    paymentMethod: "Bank Transfer",
    notes: "Net-15 terms exceeded",
  },
  {
    id: "exp-5",
    date: "2026-05-08",
    category: "Storage",
    description: "Warehouse rent — May",
    vendor: "Depósito Central SC",
    amount: 3500,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-6",
    date: "2026-05-06",
    category: "Customs",
    description: "Export documentation and clearance",
    vendor: "Aduanas Express",
    amount: 2900,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Check",
    notes: "Awaiting shipment confirmation",
  },
  {
    id: "exp-7",
    date: "2026-05-03",
    category: "Packaging",
    description: "Grain sacks and pallet wrap",
    vendor: "Empaques del Valle",
    amount: 1560,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Cash",
    notes: "",
  },
  {
    id: "exp-8",
    date: "2026-04-28",
    category: "Maintenance",
    description: "Irrigation pump repair — Plot A",
    vendor: "Servicios Hídricos López",
    amount: 2200,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-9",
    date: "2026-04-25",
    category: "Taxes",
    description: "Municipal operating permit renewal",
    vendor: "Gobierno Municipal",
    amount: 980,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-10",
    date: "2026-04-20",
    category: "Transport",
    description: "Livestock feed delivery route",
    vendor: "TransAgro Bolivia",
    amount: 1650,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  // ─── May 2026 supplements (with exp-1…exp-7 → 127,850 Bs) ───────────────────
  {
    id: "exp-2026-05-01",
    date: "2026-05-17",
    category: "Labor",
    description: "Peak harvest crews — all plots",
    vendor: "Cuadrilla Norte",
    amount: 35000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-05-02",
    date: "2026-05-11",
    category: "Supplier Payment",
    description: "Supplies — Monthly Bulk Order",
    vendor: "NutriGanado Bolivia",
    amount: 28000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-05-03",
    date: "2026-05-09",
    category: "Supplier Payment",
    description: "Fertilizer top-up — Plot C",
    vendor: "AgroInsumos SA",
    amount: 18000,
    currency: "Bs",
    status: "Overdue",
    paymentMethod: "Bank Transfer",
    notes: "Net-15 terms exceeded",
  },
  {
    id: "exp-2026-05-04",
    date: "2026-05-04",
    category: "Transport",
    description: "May distribution and export haulage",
    vendor: "TransAgro Bolivia",
    amount: 13640,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  // ─── June 2026 (130,000 Bs) ─────────────────────────────────────────────────
  {
    id: "exp-2026-06-01",
    date: "2026-06-24",
    category: "Labor",
    description: "Operational Maintenance — Field Reset",
    vendor: "Cuadrilla Norte",
    amount: 38000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-06-02",
    date: "2026-06-18",
    category: "Supplier Payment",
    description: "Feed and mineral supplements — June",
    vendor: "NutriGanado Bolivia",
    amount: 32000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-06-03",
    date: "2026-06-12",
    category: "Transport",
    description: "June export routes — Santa Cruz depot",
    vendor: "TransAgro Bolivia",
    amount: 24000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-06-04",
    date: "2026-06-08",
    category: "Fuel",
    description: "Diesel — June fleet and machinery",
    vendor: "Estación El Trigal",
    amount: 18000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-2026-06-05",
    date: "2026-06-03",
    category: "Storage",
    description: "Warehouse rent — June",
    vendor: "Depósito Central SC",
    amount: 10000,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-2026-06-06",
    date: "2026-06-01",
    category: "Customs",
    description: "Export clearance — June shipment",
    vendor: "Aduanas Express",
    amount: 8000,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Check",
    notes: "",
  },
];

export const initialReceivableRecords: ReceivableRecord[] = [
  {
    id: 1,
    customer: "Cliente Santa Cruz",
    invoiceNumber: "INV-001",
    amount: 12500,
    amountPaid: 0,
    dueDate: "May 10",
    overdueDays: 7,
    status: "Overdue",
  },
  {
    id: 2,
    customer: "Distribuidora Norte",
    invoiceNumber: "INV-002",
    amount: 8700,
    amountPaid: 0,
    dueDate: "May 28",
    overdueDays: 0,
    status: "Pending",
  },
  {
    id: 3,
    customer: "Mercado Central",
    invoiceNumber: "INV-003",
    amount: 13000,
    amountPaid: 0,
    dueDate: "Apr 28",
    overdueDays: 19,
    status: "Overdue",
  },
  {
    id: 4,
    customer: "Agro Bolivia SRL",
    invoiceNumber: "INV-004",
    amount: 9800,
    amountPaid: 9800,
    dueDate: "Apr 30",
    overdueDays: 0,
    status: "Paid",
  },
  {
    id: 5,
    customer: "Finca El Palmar",
    invoiceNumber: "INV-005",
    amount: 6700,
    amountPaid: 3500,
    dueDate: "May 25",
    overdueDays: 0,
    status: "Partially Paid",
  },
  {
    id: 6,
    customer: "Hacienda San Miguel",
    invoiceNumber: "INV-006",
    amount: 11200,
    amountPaid: 0,
    dueDate: "Jun 5",
    overdueDays: 0,
    status: "Pending",
  },
  {
    id: 7,
    customer: "Exportadora Oriente",
    invoiceNumber: "INV-007",
    amount: 7300,
    amountPaid: 0,
    dueDate: "Apr 2",
    overdueDays: 45,
    status: "Overdue",
  },
  {
    id: 8,
    customer: "Cooperativa Yungas",
    invoiceNumber: "INV-008",
    amount: 5800,
    amountPaid: 2900,
    dueDate: "May 22",
    overdueDays: 0,
    status: "Partially Paid",
  },
];

/** Default date range: full demo year (no UI wired yet) */
export const defaultDateRange = {
  startDate: "2026-01-01",
  endDate: "2026-12-31",
} as const;
