import type { ExpenseRecord, ReceivableRecord, RevenueRecord } from "./types";

export const DEFAULT_CURRENCY: "Bs" = "Bs";

export const initialRevenueRecords: RevenueRecord[] = [
  {
    id: "rev-1",
    date: "2026-05-16",
    sourceClient: "Distribuidora Norte",
    productService: "Yellow corn — 28 tons",
    category: "Export Sale",
    amount: 67200,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0412",
    notes: "FOB Santa Cruz shipment",
  },
  {
    id: "rev-2",
    date: "2026-05-14",
    sourceClient: "Mercado Central La Paz",
    productService: "White corn — wholesale lot",
    category: "Wholesale",
    amount: 38500,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0408",
    notes: "",
  },
  {
    id: "rev-3",
    date: "2026-05-12",
    sourceClient: "Agro Bolivia SRL",
    productService: "Soybean brokerage commission",
    category: "Commission",
    amount: 4200,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0405",
    notes: "Net-30 terms",
  },
  {
    id: "rev-4",
    date: "2026-05-10",
    sourceClient: "Exportadora Oriente",
    productService: "Import logistics coordination",
    category: "Import Sale",
    amount: 8900,
    currency: "Bs",
    status: "Overdue",
    paymentMethod: "Check",
    invoiceNumber: "INV-2026-0399",
    notes: "45 days outstanding",
  },
  {
    id: "rev-5",
    date: "2026-05-08",
    sourceClient: "Finca El Palmar",
    productService: "On-farm consulting — crop cycle",
    category: "Service Fee",
    amount: 5500,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Card",
    invoiceNumber: "INV-2026-0394",
    notes: "",
  },
  {
    id: "rev-6",
    date: "2026-05-05",
    sourceClient: "Cooperativa Yungas",
    productService: "Retail corn sacks — 120 units",
    category: "Retail",
    amount: 7200,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Cash",
    invoiceNumber: "INV-2026-0388",
    notes: "",
  },
  {
    id: "rev-7",
    date: "2026-05-02",
    sourceClient: "Cliente Santa Cruz",
    productService: "Corn silage — cattle feed grade",
    category: "Local Sale",
    amount: 15800,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0381",
    notes: "Awaiting delivery confirmation",
  },
  {
    id: "rev-8",
    date: "2026-04-28",
    sourceClient: "Global Grain Partners",
    productService: "Export contract — Q2 corn",
    category: "Export Sale",
    amount: 124000,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0370",
    notes: "Partial advance received",
  },
  {
    id: "rev-9",
    date: "2026-04-22",
    sourceClient: "Distribuidora Norte",
    productService: "Cancelled pre-order",
    category: "Other",
    amount: 0,
    currency: "Bs",
    status: "Cancelled",
    paymentMethod: "Other",
    invoiceNumber: "INV-2026-0355",
    notes: "Client cancelled before shipment",
  },
  {
    id: "rev-10",
    date: "2026-04-18",
    sourceClient: "Mercado Central La Paz",
    productService: "Import clearance service package",
    category: "Service Fee",
    amount: 3400,
    currency: "Bs",
    status: "Collected",
    paymentMethod: "Bank Transfer",
    invoiceNumber: "INV-2026-0348",
    notes: "",
  },
];

export const initialExpenseRecords: ExpenseRecord[] = [
  {
    id: "exp-1",
    date: "2026-05-15",
    category: "Transport",
    description: "Corn delivery to Santa Cruz depot",
    vendor: "TransAgro Bolivia",
    amount: 4200,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "Invoice #TA-2041",
  },
  {
    id: "exp-2",
    date: "2026-05-14",
    category: "Fuel",
    description: "Diesel for harvest machinery",
    vendor: "Estación El Trigal",
    amount: 1850,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Card",
    notes: "",
  },
  {
    id: "exp-3",
    date: "2026-05-12",
    category: "Labor",
    description: "Seasonal field workers — Plot B harvest",
    vendor: "Cuadrilla Norte",
    amount: 6800,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Cash",
    notes: "Due end of week",
  },
  {
    id: "exp-4",
    date: "2026-05-10",
    category: "Supplier Payment",
    description: "Fertilizer order for corn cycle",
    vendor: "AgroInsumos SA",
    amount: 12400,
    currency: "Bs",
    status: "Overdue",
    paymentMethod: "Bank Transfer",
    notes: "Net-15 terms exceeded",
  },
  {
    id: "exp-5",
    date: "2026-05-08",
    category: "Storage",
    description: "Warehouse rent — May",
    vendor: "Depósito Central SC",
    amount: 3500,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-6",
    date: "2026-05-06",
    category: "Customs",
    description: "Export documentation and clearance",
    vendor: "Aduanas Express",
    amount: 2900,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Check",
    notes: "Awaiting shipment confirmation",
  },
  {
    id: "exp-7",
    date: "2026-05-03",
    category: "Packaging",
    description: "Grain sacks and pallet wrap",
    vendor: "Empaques del Valle",
    amount: 1560,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Cash",
    notes: "",
  },
  {
    id: "exp-8",
    date: "2026-04-28",
    category: "Maintenance",
    description: "Irrigation pump repair — Plot A",
    vendor: "Servicios Hídricos López",
    amount: 2200,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-9",
    date: "2026-04-25",
    category: "Taxes",
    description: "Municipal operating permit renewal",
    vendor: "Gobierno Municipal",
    amount: 980,
    currency: "Bs",
    status: "Paid",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
  {
    id: "exp-10",
    date: "2026-04-20",
    category: "Transport",
    description: "Livestock feed delivery route",
    vendor: "TransAgro Bolivia",
    amount: 1650,
    currency: "Bs",
    status: "Pending",
    paymentMethod: "Bank Transfer",
    notes: "",
  },
];

export const initialReceivableRecords: ReceivableRecord[] = [
  {
    id: 1,
    customer: "Cliente Santa Cruz",
    invoiceNumber: "INV-001",
    amount: 12500,
    amountPaid: 0,
    dueDate: "May 10",
    overdueDays: 7,
    status: "Overdue",
  },
  {
    id: 2,
    customer: "Distribuidora Norte",
    invoiceNumber: "INV-002",
    amount: 8700,
    amountPaid: 0,
    dueDate: "May 28",
    overdueDays: 0,
    status: "Pending",
  },
  {
    id: 3,
    customer: "Mercado Central",
    invoiceNumber: "INV-003",
    amount: 13000,
    amountPaid: 0,
    dueDate: "Apr 28",
    overdueDays: 19,
    status: "Overdue",
  },
  {
    id: 4,
    customer: "Agro Bolivia SRL",
    invoiceNumber: "INV-004",
    amount: 9800,
    amountPaid: 9800,
    dueDate: "Apr 30",
    overdueDays: 0,
    status: "Paid",
  },
  {
    id: 5,
    customer: "Finca El Palmar",
    invoiceNumber: "INV-005",
    amount: 6700,
    amountPaid: 3500,
    dueDate: "May 25",
    overdueDays: 0,
    status: "Partially Paid",
  },
  {
    id: 6,
    customer: "Hacienda San Miguel",
    invoiceNumber: "INV-006",
    amount: 11200,
    amountPaid: 0,
    dueDate: "Jun 5",
    overdueDays: 0,
    status: "Pending",
  },
  {
    id: 7,
    customer: "Exportadora Oriente",
    invoiceNumber: "INV-007",
    amount: 7300,
    amountPaid: 0,
    dueDate: "Apr 2",
    overdueDays: 45,
    status: "Overdue",
  },
  {
    id: 8,
    customer: "Cooperativa Yungas",
    invoiceNumber: "INV-008",
    amount: 5800,
    amountPaid: 2900,
    dueDate: "May 22",
    overdueDays: 0,
    status: "Partially Paid",
  },
];

/** Default date range: full demo year (no UI wired yet) */
export const defaultDateRange = {
  startDate: "2026-01-01",
  endDate: "2026-12-31",
} as const;
